version: '3.9'
services:
  postgres:
    image: postgres:14.2
    # image: postgis/postgis:14-3.4
    container_name: star_postgres
    # restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=!@#123qwe
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - star-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: star_pgadmin
    # restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "!@#123qwe"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:8080"
    networks:
      - star-postgres
    depends_on:
      postgres:
        condition: service_healthy
  blackfriday:
    image: blackfriday
    container_name: blackfriday
    ports:
      - "8080:80"
    networks:
      - star-postgres


networks:
  star-postgres:
    driver: bridge

volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./postgresql_data"
  pgadmin-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./pgadmin_data"